<?php

namespace AppBundle\Repository;

/**
 * FaucetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaucetRepository extends \Doctrine\ORM\EntityRepository
{
}
