<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Faucet;
use DateTime;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;

/**
 * FaucetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
// class FaucetRepository extends \Doctrine\ORM\EntityRepository
class FaucetRepository extends ServiceEntityRepository
{

	public function __construct( RegistryInterface $registry){
        parent::__construct($registry, Faucet::class);
    }

	public function getNullFaucet(){
		$faucet	= new Faucet();
		$dt_now	= new DateTime();

		$faucet->setUrl('');
		$faucet->setDuration( 1800 );

		$faucet->setUpdated( $dt_now );
		$faucet->setUntil( $dt_now );
		$faucet->setBanUntil( new DateTime(date('Y-m-d H:i:s', strtotime( '-1 day' ))) );

		$faucet->setPriority( 1 );
		$faucet->setIsDebt( false );

		return $faucet;
	}
//______________________________________________________________________________

	public function removeFaucet( $id ){
		$faucet	= $this->_em->getRepository(Faucet::class)->find( $id );
		$this->_em->remove( $faucet );
		$this->_em->flush();
	}
//______________________________________________________________________________



}
