<?php

namespace AppBundle\Repository;

/**
 * FuacetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuacetRepository extends \Doctrine\ORM\EntityRepository
{
}
